# .travis.yml
language: go


script:
  - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux